name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Or the branch you are using for development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure this matches your project's Node version

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Export the static site
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Specify the branch to deploy to
          publish_dir: ./out  # Ensure this is the directory with your static site files
